version: "3.6"

services:
  typo3:
    image: martinhelmich/typo3:13
    ports:
      - 3020:80
    volumes:
      - ./data/fileadmin:/var/www/html/fileadmin
      - ./data/typo3conf:/var/www/html/typo3conf
      - ./data/uploads:/var/www/html/uploads
    networks:
      - backend

  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
